import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { GrSearch } from "react-icons/gr";
import BgJpg from "../public/bg.jpg";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    });
    setCity("");
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Luth Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Overlay */}
      <div className="absolute top-0 bottom-0 right-0 left-0 bg-white/40 z-[1]" />
      {/* Background Image */}
      <Image src={BgJpg} alt="Weather Jpg" layout="fill" className="object-cover" />
      {/* Search */}
      <div>
        <form>
          <div>
            <input type="search" placeholder="Search your city" />
          </div>
          <button>
            <GrSearch />
          </button>
        </form>
      </div>
    </>
  );
}
