import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { GrSearch } from "react-icons/gr";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
  };

  return (
    <>
      <Head>
        <title>Luth Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="flex justify-center items-center h-screen">Hello World</h1>
    </>
  );
}
